name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: https://staysync.me/api
          NODE_ENV: production
          CORS_ORIGIN: https://staysync.me,http://localhost:3000

      - name: Create 404.html
        run: |
          cp build/index.html build/404.html
          echo "<base href=\"/\" />" >> build/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: staysync.me 