name: Deploy React App to GitHub Pages (Manual)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # (중요) build 폴더를 'github-pages'라는 이름으로 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages   # actions/deploy-pages@v3가 기본으로 찾는 이름
          path: build         # CRA로 생성된 빌드 폴더 (상대 경로)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
