name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push될 때만 실행 (원하시는 브랜치로 조정)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # CRA 빌드 결과물 경로!
          publish_branch: gh-pages # gh-pages 브랜치로 배포!

